### ISSUE TITLE
install vagrant-berkshelf hitting gem dependency errors

### ISSUE THREAD

**Issue by mnp** [shedd/duckpan-vagrant#27]
Ubuntu 14.04.1 LTS, following the readme, stuck at step 5.

```sh
$ vagrant plugin install vagrant-berkshelf --plugin-version=2.0.1
Installing the 'vagrant-berkshelf --version '2.0.1'' plugin. This can take a few minutes...
/usr/lib/ruby/1.9.1/rubygems/dependency_installer.rb:153:in `gather_dependencies': Unable to resolve dependencies: vagrant-berkshelf requires celluloid (~> 0.16.0.pre), celluloid-io (~> 0.16.0.pre); berkshelf requires addressable (~> 2.3.4), berkshelf-api-client (~> 1.2), buff-config (~> 1.0), buff-extensions (~> 1.0), buff-shell_out (~> 0.1), cleanroom (~> 1.0), faraday (~> 0.9.0), minitar (~> 0.5.4), retryable (~> 1.3.3), ridley (~> 4.0), solve (~> 1.1), thor (~> 0.19), octokit (~> 3.0), celluloid (~> 0.16.0), celluloid-io (~> 0.16.1) (Gem::DependencyError)
	from /usr/lib/ruby/1.9.1/rubygems/dependency_installer.rb:267:in `install'
	from /usr/share/vagrant/plugins/commands/plugin/action/install_gem.rb:65:in `block in call'
	from /usr/share/vagrant/plugins/commands/plugin/gem_helper.rb:42:in `block in with_environment'
	from /usr/lib/ruby/1.9.1/rubygems/user_interaction.rb:40:in `use_ui'
	from /usr/share/vagrant/plugins/commands/plugin/gem_helper.rb:41:in `with_environment'
	from /usr/share/vagrant/plugins/commands/plugin/action/install_gem.rb:52:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/plugins/commands/plugin/action/bundler_check.rb:20:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builder.rb:116:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:69:in `block in run'
	from /usr/lib/ruby/vendor_ruby/vagrant/util/busy.rb:19:in `busy'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:69:in `run'
	from /usr/share/vagrant/plugins/commands/plugin/command/base.rb:17:in `action'
	from /usr/share/vagrant/plugins/commands/plugin/command/install.rb:27:in `execute'
	from /usr/share/vagrant/plugins/commands/plugin/command/root.rb:56:in `execute'
	from /usr/lib/ruby/vendor_ruby/vagrant/cli.rb:38:in `execute'
	from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:484:in `cli'
	from /usr/bin/vagrant:127:in `<main>'
```

**Comment by shedd** [comment]
fix pending merge: https://github.com/shedd/duckpan-vagrant/pull/32
